package com.saidim.nawa.media.remote.album

data class Song(
    val starred: Boolean? = null,
    val popularity: Double? = null,
    val starredNum: Int? = null,
    val playedNum: Int? = null,
    val dayPlays: Int? = null,
    val hearTime: Int? = null,
    val mp3Url: String? = null,
    val rtUrls: Any? = null,
    val mark: Long? = null,
    val noCopyrightRcmd: Any? = null,
    val originCoverType: Int? = null,
    val originSongSimpleData: Any? = null,
    val songJumpInfo: Any? = null,
    val rtype: Int? = null,
    val rurl: Any? = null,
    val crbt: Any? = null,
    val rtUrl: Any? = null,
    val ftype: Int? = null,
    val bMusic: BMusic? = null,
    val sqMusic: Any? = null,
    val hrMusic: Any? = null,
    val alias: List<Any>? = null,
    val artists: List<Artist>? = null,
    val copyrightId: Int? = null,
    val album: AlbumX? = null,
    val score: Int? = null,
    val hMusic: HMusic? = null,
    val mMusic: MMusic? = null,
    val lMusic: LMusic? = null,
    val audition: Any? = null,
    val copyFrom: String? = null,
    val ringtone: Any? = null,
    val disc: String? = null,
    val no: Int? = null,
    val fee: Int? = null,
    val commentThreadId: String? = null,
    val mvid: Int? = null,
    val duration: Int? = null,
    val position: Int? = null,
    val status: Int? = null,
    val name: String? = null,
    val id: Long = 0
)